name: talknotes_flutter
description: "Enterprise-level TalkNotes Flutter application for AI-powered voice notes"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  equatable: ^2.0.5

  # Dependency Injection
  get_it: ^7.6.0
  injectable: ^2.3.2

  # Network & API Integration
  dio: ^5.3.2
  retrofit: ^4.0.3
  pretty_dio_logger: ^1.3.1
  connectivity_plus: ^5.0.1

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2

  # Navigation & Routing
  auto_route: ^7.7.1

  # Code Generation & Serialization
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  # Audio Features (Core to TalkNotes)
  record: ^6.1.1
  audioplayers: ^5.2.1
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  file_picker: ^8.1.2

  # UI & Animation
  flutter_animate: ^4.2.0+1
  shimmer: ^3.0.0
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  lottie: ^2.7.0
  loading_animation_widget: ^1.2.0+4

  # Utilities
  dartz: ^0.10.1
  intl: ^0.18.1
  uuid: ^4.1.0
  logger: ^2.0.2+1

  # Form Validation
  formz: ^0.6.1

  # Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  injectable_generator: ^2.4.1
  retrofit_generator: ^8.0.4
  auto_route_generator: ^7.2.0
  hive_generator: ^2.0.1

  # Testing
  mocktail: ^1.0.0
  bloc_test: ^9.1.5

  # Linting & Code Quality
  flutter_lints: ^5.0.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/audio/
    - assets/icons/
    - assets/animations/
